// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: BodyType.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BodyType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon      string     `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	TimeStamp *TimeStamp `protobuf:"bytes,4,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *BodyType) Reset() {
	*x = BodyType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BodyType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyType) ProtoMessage() {}

func (x *BodyType) ProtoReflect() protoreflect.Message {
	mi := &file_BodyType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyType.ProtoReflect.Descriptor instead.
func (*BodyType) Descriptor() ([]byte, []int) {
	return file_BodyType_proto_rawDescGZIP(), []int{0}
}

func (x *BodyType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BodyType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BodyType) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *BodyType) GetTimeStamp() *TimeStamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type BodyTypeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BodyTypes []*BodyType `protobuf:"bytes,1,rep,name=bodyTypes,proto3" json:"bodyTypes,omitempty"`
}

func (x *BodyTypeList) Reset() {
	*x = BodyTypeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BodyType_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyTypeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyTypeList) ProtoMessage() {}

func (x *BodyTypeList) ProtoReflect() protoreflect.Message {
	mi := &file_BodyType_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyTypeList.ProtoReflect.Descriptor instead.
func (*BodyTypeList) Descriptor() ([]byte, []int) {
	return file_BodyType_proto_rawDescGZIP(), []int{1}
}

func (x *BodyTypeList) GetBodyTypes() []*BodyType {
	if x != nil {
		return x.BodyTypes
	}
	return nil
}

var File_BodyType_proto protoreflect.FileDescriptor

var file_BodyType_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x42, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x1a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x08, 0x42, 0x6f, 0x64,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x2f, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3e,
	0x0a, 0x0c, 0x42, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x73, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_BodyType_proto_rawDescOnce sync.Once
	file_BodyType_proto_rawDescData = file_BodyType_proto_rawDesc
)

func file_BodyType_proto_rawDescGZIP() []byte {
	file_BodyType_proto_rawDescOnce.Do(func() {
		file_BodyType_proto_rawDescData = protoimpl.X.CompressGZIP(file_BodyType_proto_rawDescData)
	})
	return file_BodyType_proto_rawDescData
}

var file_BodyType_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_BodyType_proto_goTypes = []interface{}{
	(*BodyType)(nil),     // 0: models.BodyType
	(*BodyTypeList)(nil), // 1: models.BodyTypeList
	(*TimeStamp)(nil),    // 2: models.TimeStamp
}
var file_BodyType_proto_depIdxs = []int32{
	2, // 0: models.BodyType.timeStamp:type_name -> models.TimeStamp
	0, // 1: models.BodyTypeList.bodyTypes:type_name -> models.BodyType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_BodyType_proto_init() }
func file_BodyType_proto_init() {
	if File_BodyType_proto != nil {
		return
	}
	file_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_BodyType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_BodyType_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyTypeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BodyType_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BodyType_proto_goTypes,
		DependencyIndexes: file_BodyType_proto_depIdxs,
		MessageInfos:      file_BodyType_proto_msgTypes,
	}.Build()
	File_BodyType_proto = out.File
	file_BodyType_proto_rawDesc = nil
	file_BodyType_proto_goTypes = nil
	file_BodyType_proto_depIdxs = nil
}
