// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: Car.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelId        int32      `protobuf:"varint,3,opt,name=modelId,proto3" json:"modelId,omitempty"`
	ColorId        int32      `protobuf:"varint,4,opt,name=colorId,proto3" json:"colorId,omitempty"`
	ManufacturerId int32      `protobuf:"varint,5,opt,name=manufacturerId,proto3" json:"manufacturerId,omitempty"`
	AcHeater       bool       `protobuf:"varint,6,opt,name=ac_heater,json=acHeater,proto3" json:"ac_heater,omitempty"`
	BodyTypeId     int32      `protobuf:"varint,7,opt,name=bodyTypeId,proto3" json:"bodyTypeId,omitempty"`
	TimeStamp      *TimeStamp `protobuf:"bytes,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Car_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_Car_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_Car_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Car) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *Car) GetColorId() int32 {
	if x != nil {
		return x.ColorId
	}
	return 0
}

func (x *Car) GetManufacturerId() int32 {
	if x != nil {
		return x.ManufacturerId
	}
	return 0
}

func (x *Car) GetAcHeater() bool {
	if x != nil {
		return x.AcHeater
	}
	return false
}

func (x *Car) GetBodyTypeId() int32 {
	if x != nil {
		return x.BodyTypeId
	}
	return 0
}

func (x *Car) GetTimeStamp() *TimeStamp {
	if x != nil {
		return x.TimeStamp
	}
	return nil
}

type CarList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars []*Car `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
}

func (x *CarList) Reset() {
	*x = CarList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Car_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarList) ProtoMessage() {}

func (x *CarList) ProtoReflect() protoreflect.Message {
	mi := &file_Car_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarList.ProtoReflect.Descriptor instead.
func (*CarList) Descriptor() ([]byte, []int) {
	return file_Car_proto_rawDescGZIP(), []int{1}
}

func (x *CarList) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

var File_Car_proto protoreflect.FileDescriptor

var file_Car_proto_rawDesc = []byte{
	0x0a, 0x09, 0x43, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x1a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6c,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61,
	0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x63, 0x5f, 0x68, 0x65, 0x61, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x61, 0x63, 0x48, 0x65, 0x61, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6f, 0x64,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62,
	0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2a, 0x0a, 0x07, 0x43, 0x61,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x61, 0x72,
	0x52, 0x04, 0x63, 0x61, 0x72, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Car_proto_rawDescOnce sync.Once
	file_Car_proto_rawDescData = file_Car_proto_rawDesc
)

func file_Car_proto_rawDescGZIP() []byte {
	file_Car_proto_rawDescOnce.Do(func() {
		file_Car_proto_rawDescData = protoimpl.X.CompressGZIP(file_Car_proto_rawDescData)
	})
	return file_Car_proto_rawDescData
}

var file_Car_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Car_proto_goTypes = []interface{}{
	(*Car)(nil),       // 0: models.Car
	(*CarList)(nil),   // 1: models.CarList
	(*TimeStamp)(nil), // 2: models.TimeStamp
}
var file_Car_proto_depIdxs = []int32{
	2, // 0: models.Car.timeStamp:type_name -> models.TimeStamp
	0, // 1: models.CarList.cars:type_name -> models.Car
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Car_proto_init() }
func file_Car_proto_init() {
	if File_Car_proto != nil {
		return
	}
	file_TimeStamp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Car_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Car_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Car_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Car_proto_goTypes,
		DependencyIndexes: file_Car_proto_depIdxs,
		MessageInfos:      file_Car_proto_msgTypes,
	}.Build()
	File_Car_proto = out.File
	file_Car_proto_rawDesc = nil
	file_Car_proto_goTypes = nil
	file_Car_proto_depIdxs = nil
}
